# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e6b822e193b4fc83c8968055355755b6799ce37ef06c2c98d4758214fd078178c92cff4099bb870cd39d6da999c14da26c60162ca10471790b13654f99cb4a5

test:
  secret_key_base: 3c51e6c7e04722b44ca13dcde5cd0718064cd987795aa0259244599de0a8dff6e337f89ee9195ad613cf58a1e0eaea41cb3b7c16eb74e66c51fab4d51be6ff6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
